### PR TITLE
Added Laravel artisan commands assertions

### PR DESCRIPTION
**Pull request by jetexe**
Добавлены ассерты для работы с артизан-коммандами:

- assertArtisanCommandExists
- assertArtisanCommandHasOption
- assertArtisanCommandHasArgument
- assertArtisanCommandHasOptionShortcut
- assertArtisanCommandShortcutBelongToOption
- assertArtisanCommandDescriptionNotEmpty
- assertArtisanCommandDescriptionRegExp

### CODE REVIEW

**Comment by tarampampam** [comment]
@jetexe 

Changeslog?
Reademe update?

**Comment by tarampampam** [comment]
Target branch: `v1`

**Comment by jetexe** [comment]
@tarampampam, readme updated. Changes are detailed in first PR comment

**Comment by tarampampam** [comment]
Merged! THX for your PR!

**Pull request merged**
